### ISSUE TITLE
Incorrect MKLROOT in CMakeLists.txt

### ISSUE THREAD

**Issue by amirmasud** [sympiler/sympiler#1]
Dear Kazem, 

It seems you used the parent directory of `MKLROOT` (which is e.g. `/opt/intel` instead of `/opt/intel/mkl`) as `MKLROOT` and used it in the other statements afterward.

https://github.com/sympiler/sympiler/blob/abdee268dc18826bfd208fdf7a7b1a90c9a1f1fd/CMakeLists.txt#L4

Since `MKLROOT` is an env and can be used by other apps, I think it's better to correct it.

**Comment by cheshmi** [comment]
Hi Amir,
Thank you for bringing this issue up.
This is a known issue and we have changed the build system. I will update the repo with the new version soon.
