### ISSUE TITLE
How to ues sympiler for kernel fusion(SC23)?

### ISSUE THREAD

**Issue by Corange508** [sympiler/sympiler#12]
Dear Cheshmi,

I recently came across your paper on kernel fusion presented at SC23, where it was mentioned that the relevant code has been integrated into Sympiler. However, upon reviewing the Sympiler documentation, I noticed that the section on kernel fusion is marked as "Not public yet."

Could you please provide guidance on how to utilize the kernel fusion feature within Sympiler? 
Thank you！

**Comment by cheshmi** [comment]
Hello,

The artifact is available from [here](https://github.com/cheshmi/sc23-ad-sparse-fusion). It is not yet integrated to the main Sympiler repository.
